// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmWPPQlC_O4Z_F1aVJYRKHrRArU55g6iA',
    appId: '1:259363661016:web:3f1c32428cbab05f93e3ad',
    messagingSenderId: '259363661016',
    projectId: 'project-one-3daee',
    authDomain: 'project-one-3daee.firebaseapp.com',
    storageBucket: 'project-one-3daee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOVqXXR2CIqlc1-70YKr_TpY3ujGv1TuE',
    appId: '1:259363661016:android:9f774d2a1093d4df93e3ad',
    messagingSenderId: '259363661016',
    projectId: 'project-one-3daee',
    storageBucket: 'project-one-3daee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt6ciyRk_xNgthWl1GCUIgUXuTvnGJCwU',
    appId: '1:259363661016:ios:5d72dd35fd7eb79193e3ad',
    messagingSenderId: '259363661016',
    projectId: 'project-one-3daee',
    storageBucket: 'project-one-3daee.firebasestorage.app',
    iosBundleId: 'com.example.projectOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt6ciyRk_xNgthWl1GCUIgUXuTvnGJCwU',
    appId: '1:259363661016:ios:5d72dd35fd7eb79193e3ad',
    messagingSenderId: '259363661016',
    projectId: 'project-one-3daee',
    storageBucket: 'project-one-3daee.firebasestorage.app',
    iosBundleId: 'com.example.projectOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmWPPQlC_O4Z_F1aVJYRKHrRArU55g6iA',
    appId: '1:259363661016:web:84f385f359dec69793e3ad',
    messagingSenderId: '259363661016',
    projectId: 'project-one-3daee',
    authDomain: 'project-one-3daee.firebaseapp.com',
    storageBucket: 'project-one-3daee.firebasestorage.app',
  );

}